### ISSUE TITLE
1PPS-DPLL Parameters

### ISSUE THREAD

**Issue by Ah-san-Ah-med** [MorrisMA/1PPS-DPLL#1]
Hello,
I am unable to find that why the NCO Out frequency duty cycle is changing when configured for 10MHz@1MHz. Any help will be appreciated. thanks in advance

**Comment by MorrisMA** [comment]
The issue is that the frequency of the underlying reference clock is not actually changing. Therefore, the DPLL output is never a 50% duty cycle signal as would be expected if the reference clock frequency was actually being changed when phase adjustments are made to the DPLL. As the output frequency is increased, the resulting duty cycle variations become much more prominent and easily seen on an oscilloscope or similar instrument.
